import './globals.css'
import store from './store'
import { Provider } from 'react-redux'

export const metadata = {
  title: 'Работа в Казахстане, поиск персонала и публикация вакансий - hh.kz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  )
}
